import type { Metadata } from "next";
import "./globals.css";
import SubscribeBanner from "@components/layout/SubscribeBanner";
import NavBar from "@components/layout/NavBar";
import Footer from "@components/layout/Footer";

export const metadata: Metadata = {
    title: "AI Blog",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/images/logo3.png" type="image/x-icon" />

            </head>

            <body
            >
                <SubscribeBanner />
                <NavBar />
                <div className="pt-[100px] bg-deepblack">
                    {children}

                </div>
                <Footer />
            </body>
        </html>
    );
}
