import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@components/layout/NavBar";
import Footer from "@components/layout/Footer";
import BloggerModal from "@components/layout/BloggerModal";
import { SubscribeBanner } from "@components/layout/SubscribeBanner";
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs'

export const metadata: Metadata = {
    title: "AI Blog",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <head>
                    <link rel="icon" href="/images/logo3.png" type="image/x-icon" />

                </head>

                <body
                >
                    <SubscribeBanner />
                    <NavBar />
                    <BloggerModal />
                    <div className="pt-[100px] bg-deepblack">
                        {children}

                    </div>
                    <Footer />
                </body>
            </html>
        </ClerkProvider>
    );
}
